#!/usr/bin/python

import sys, os, os.path

def mydir():
	return os.path.dirname(os.path.abspath(__file__))

if len(sys.argv)<4 or sys.argv[1]=='-h' or sys.argv[1]=='--help':
	print "Usage:\n{0} node disk backing-store [directory]\n".format(os.path.basename(__file__))
	sys.exit(0)

node = sys.argv[1]
disk = sys.argv[2]
store = os.path.abspath(sys.argv[3])
if len(sys.argv)>=5:
	dir = sys.argv[4]
else:	
	dir = mydir() + '/targets.d'

if not os.path.exists(store) or os.path.isdir(store):
	print "Backing store must exist and must NOT be directory: '{0}'".format(store)
	sys.exit(1)

dir=os.path.join(dir, node)
if not os.path.isdir(dir):
	print "config directory NOT exists: '{0}'".format(dir)
	sys.exit(1)

cfile=os.path.join(dir, disk)
if os.path.exists(cfile):
	print "config file ALREADY exists: '{0}'".format(cfile)
	sys.exits(1)

print "symlink('{0}', '{1}')".format(store, cfile)
os.symlink(store, cfile)i


