#!/usr/bin/python

import sys, os, os.path


def logAndCall(func):
	def docall(*arguments, **namedArguments):
        	print "log: %s(*%s, **%s)" %\
                      (func.__name__, arguments, namedArguments)
        	func(*arguments, **namedArguments)
	return docall

def mydir():
	return os.path.dirname(os.path.abspath(__file__))

argc=len(sys.argv)
if argc<3 or sys.argv[1]=='-h' or sys.argv[1]=='--help':
	print "Usage:\n{0} node disk [directory]\n".format(os.path.basename(__file__))
	sys.exit(0)

node = sys.argv[1]
disk = sys.argv[2]
dir = argc>=4 and sys.argv[4] or os.path.join(mydir(), 'targets.d')

dir=os.path.join(dir, node)
if not os.path.isdir(dir):
	print "config directory NOT exists: '{0}'".format(dir)
	sys.exit(1)

cfile=os.path.join(dir, disk)
if not os.path.exists(cfile):
	print "config file NOT exists: '{0}'".format(cfile)
	sys.exit(1)

#print "os.symlink('{0}', '{1}')".format(store, cfile)
os.remove=logAndCall(os.remove)
os.remove(cfile)


